export default [
    { text: 'Java', value: 6 },
    { text: 'Python', value: 6 },
    { text: 'Typescript', value: 6 },
    { text: 'ReactJS', value: 6 },
    { text: 'AWS', value: 4 },
    { text: 'Lambda', value: 4 },
    { text: 'GraphQL', value: 4 },
    { text: 'CDK', value: 4 },
    { text: 'CICD', value: 4 },
    { text: 'Docker', value: 4 },
    { text: 'dynamodb', value: 3 },
    { text: 'NodeJS', value: 3 },
    { text: 'S3', value: 3 },
    { text: 'VPC', value: 3 },
    { text: 'Redux', value: 3 },
    { text: 'Fargate', value: 3 },
    { text: 'SQL', value: 3 },
    { text: 'Route54', value: 2 },
    { text: 'Javascript', value: 2 },
    { text: 'Cloudwatch', value: 2 },
    { text: 'Cloudformation', value: 2 },
    { text: 'Amplify', value: 2 },
    { text: 'Rest API', value: 2 },
    { text: 'RDS', value: 2 },
    { text: 'Redshift', value: 2 },
    { text: 'Pipeline', value: 2 },
    { text: 'HTML', value: 2 },
    { text: 'CSS', value: 2 },
    { text: 'SNS', value: 2 },
    { text: 'SQS', value: 2 },
    { text: 'DNS', value: 2 },
]